import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import ApolloProviderWrapper from "../components/ApolloProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Just cause this is a client component 
    // and the things in it may not be
    // it doesn't matter, Next.js is 
    // smart enough to sperate it
    <ApolloProviderWrapper>
      <ClerkProvider>
        <html lang="en">
          <body className="min-h-screen flex">
            {children}
            {/* Toaster */}
          </body>
        </html>
      </ClerkProvider>
    </ApolloProviderWrapper>
  );
}
